# Generated by Django 5.0.4 on 2024-05-07 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailservice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingsettings",
            name="date_and_time",
            field=models.DateField(
                default=django.utils.timezone.now,
                verbose_name="дата и время первой рассылки",
            ),
        ),
    ]
