# Generated by Django 5.0.6 on 2024-05-11 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailservice", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logs",
            options={
                "verbose_name": "попытка рассылки",
                "verbose_name_plural": "попытки рассылки",
            },
        ),
        migrations.RemoveField(
            model_name="logs",
            name="client",
        ),
        migrations.AddField(
            model_name="logs",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="logs",
            name="status",
            field=models.CharField(
                choices=[("success", "Успешно"), ("fail", "Не успешно")],
                max_length=50,
                verbose_name="статус",
            ),
        ),
    ]
