# Generated by Django 5.0.4 on 2024-05-09 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailservice", "0002_alter_mailingsettings_date_and_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingsettings",
            name="create_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="дата создания рассылки"
            ),
        ),
    ]
