# Generated by Django 5.0.6 on 2024-05-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailservice", "0003_remove_message_mailing_settings_client_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingsettings",
            options={
                "permissions": [
                    ("set_deactivate", "Can deactivate mailing"),
                    ("view_all_mailings", "Can view all mailing"),
                ],
                "verbose_name": "настройка рассылки",
                "verbose_name_plural": "настройки рассылки",
            },
        ),
    ]
