# Generated by Django 5.0.6 on 2024-05-15 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailservice", "0004_alter_mailingsettings_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingsettings",
            name="sent_time",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="время отправки рассылки",
            ),
        ),
    ]
