# Generated by Django 5.0.6 on 2024-05-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailservice", "0005_mailingsettings_sent_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailingsettings",
            name="date_and_time",
        ),
    ]
